from .vehiculo import Vehiculo
from .tipoVehiculo import TipoVehiculo
from .claseVehiculo import ClaseVehiculo
from .inventario import Inventario
from .persona import Persona
from .ordenCompra import OrdenCompra
from .factura import Factura
from .tipoPago import TipoPago
from .envio import Envio
from .trazabilidad import Trazabilidad
