from .claseVehiculo import ClaseVehiculo
from .envio import Envio
from .factura import Factura
from .inventario import Inventario
from .ordenCompra import OrdenCompra
from .persona import Persona
from .tipoPago import TipoPago
from .tipoVehiculo import TipoVehiculo
from .trazabilidad import Trazabilidad
from .vehiculo import Vehiculo
