# Generated by Django 4.1.3 on 2022-11-05 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClaseVehiculo",
            fields=[
                ("codigo", models.IntegerField(primary_key=True, serialize=False)),
                ("descripcion", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Persona",
            fields=[
                ("cc", models.BigIntegerField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("telefono", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("direccion", models.CharField(max_length=200)),
                ("codigo_postal", models.CharField(max_length=8)),
                ("rol", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="TipoPago",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("tipo", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="TipoVehiculo",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("estado", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Trazabilidad",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("estado", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("marca", models.CharField(max_length=40)),
                ("modelo_vehiculo", models.CharField(max_length=30)),
                ("año_modelo", models.CharField(max_length=5)),
                ("num_pasajeros", models.CharField(max_length=3)),
                ("color", models.CharField(max_length=30)),
                ("matricula", models.CharField(max_length=8)),
                ("clases_servicios", models.CharField(max_length=40)),
                ("kilometraje", models.CharField(max_length=40)),
                ("cilindraje", models.CharField(max_length=40)),
                (
                    "clase_vehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appVehiculo.clasevehiculo",
                    ),
                ),
                (
                    "tipo_vehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appVehiculo.tipovehiculo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrdenCompra",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("fecha", models.DateField()),
                ("cantidad", models.BigIntegerField()),
                ("descripcion", models.CharField(max_length=254)),
                ("precio_unitario", models.FloatField()),
                ("impuestos", models.FloatField()),
                ("valor_total", models.FloatField()),
                (
                    "persona_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appVehiculo.persona",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inventario",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("fecha_lote", models.DateField(auto_now_add=True)),
                (
                    "persona_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appVehiculo.persona",
                    ),
                ),
                (
                    "vehiculo_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appVehiculo.vehiculo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Factura",
            fields=[
                (
                    "num_factura",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("fecha_factura", models.DateTimeField(auto_now=True)),
                ("producto", models.CharField(max_length=255)),
                ("otros_costos", models.FloatField()),
                ("valor_factura", models.FloatField()),
                (
                    "orden_compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appVehiculo.ordencompra",
                    ),
                ),
                (
                    "persona_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appVehiculo.persona",
                    ),
                ),
                (
                    "tipo_pago_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appVehiculo.tipopago",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Envio",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("remitente", models.CharField(max_length=255)),
                ("destinatario", models.CharField(max_length=255)),
                (
                    "factura_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appVehiculo.factura",
                    ),
                ),
                (
                    "trazabilidad_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appVehiculo.trazabilidad",
                    ),
                ),
            ],
        ),
    ]
